server:
  port: 9898
spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: sa
    url: jdbc:h2:mem:testdb
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    username: sahilpratap123yadav@gmail.com
    password: kwjzsbwzfhfxdlze
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
